version: "3"

networks:
  loki:

services:
  python_app:
    image: nikolina2k/ma-repo:latest
    container_name: python_app
    ports:
      - "8000:8000"
    logging: &logger
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  typescript_app:
    image: nikolina2k/cat-pics:latest
    container_name: cat-pics
    ports:
      - "8080:8080"
    logging:
      <<: *logger

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging:
      <<: *logger

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./config/promtail:/etc/promtail/config
    command: -config.file=/etc/promtail/config/promtail.yaml
    networks:
      - loki
    logging:
      <<: *logger

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    networks:
      - loki
    logging:
      <<: *logger