apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
spec:
  selector:
    app: "{{ .Values.metaData.appName }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: LoadBalancer